name: NPR Scraper

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every hour
  workflow_dispatch:

jobs:
  scrape_and_generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: python npr_corrections_scraper.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update RSS feed" || echo "No changes to commit"
        git push
